import { AnimationSequence } from '../types/animations';

export const photosynthesisAnimation: AnimationSequence = {
  id: 'photosynthesis-001',
  title: 'Photosynthesis Process',
  topic: 'Biology - Photosynthesis',
  description: 'Step-by-step visualization of how plants convert sunlight into energy',
  totalSteps: 5,
  autoPlay: false,
  difficulty: 'intermediate',
  tags: ['biology', 'energy', 'plants'],
  steps: [
    {
      id: 'ps-1',
      step: 1,
      title: 'Sunlight Absorption',
      description: 'Chlorophyll in the leaf absorbs sunlight energy.',
      narration: "Let's start with sunlight. Chlorophyll molecules in the leaf absorb photons from the sun.",
      animationType: 'fade-in',
      trigger: 'click',
      duration: 1,
      elements: [
        {
          id: 'sun',
          type: 'shape',
          content: '☀️',
          x: 20,
          y: 20,
          width: 80,
          height: 80,
          color: '#FFD700',
        },
        {
          id: 'leaf',
          type: 'shape',
          content: '🍃',
          x: 60,
          y: 50,
          width: 100,
          height: 100,
          color: '#228B22',
        },
      ],
      quiz: {
        question: 'What molecule absorbs sunlight in plants?',
        options: ['Chlorophyll', 'Glucose', 'Oxygen', 'Water'],
        correct: 0,
      },
    },
    {
      id: 'ps-2',
      step: 2,
      title: 'CO₂ Enters the Leaf',
      description: 'Carbon dioxide from the air enters the leaf through stomata.',
      narration: 'Carbon dioxide enters through small pores called stomata.',
      animationType: 'slide-left',
      trigger: 'click',
      duration: 1.5,
      delay: 0.3,
      elements: [
        {
          id: 'co2',
          type: 'text',
          content: 'CO₂',
          x: 10,
          y: 60,
          color: '#666',
        },
        {
          id: 'arrow',
          type: 'text',
          content: '→',
          x: 50,
          y: 60,
          color: '#E63946',
        },
      ],
    },
    {
      id: 'ps-3',
      step: 3,
      title: 'Light Reactions',
      description: 'Energy from sunlight splits water molecules and produces ATP.',
      narration: 'Light reactions occur in the thylakoids, where water is split.',
      animationType: 'pulse',
      trigger: 'click',
      duration: 2,
      elements: [
        {
          id: 'water-molecules',
          type: 'text',
          content: 'H₂O',
          x: 40,
          y: 40,
          color: '#4169E1',
        },
        {
          id: 'atp-production',
          type: 'text',
          content: 'ATP ⚡',
          x: 60,
          y: 40,
          color: '#FFD700',
        },
      ],
    },
    {
      id: 'ps-4',
      step: 4,
      title: 'Dark Reactions (Calvin Cycle)',
      description: 'CO₂ is converted into glucose using ATP and NADPH.',
      narration: 'The Calvin cycle uses the energy from light reactions to produce glucose.',
      animationType: 'fade-in',
      trigger: 'click',
      duration: 1.5,
      elements: [
        {
          id: 'cycle',
          type: 'text',
          content: 'Calvin Cycle',
          x: 35,
          y: 50,
          color: '#228B22',
        },
        {
          id: 'glucose-out',
          type: 'text',
          content: '→ C₆H₁₂O₆',
          x: 60,
          y: 50,
          color: '#FF6347',
        },
      ],
    },
    {
      id: 'ps-5',
      step: 5,
      title: 'Energy Storage',
      description: 'Glucose is stored or used by the plant for growth and energy.',
      narration: 'The glucose produced is either used for energy or stored for later use.',
      animationType: 'scale',
      trigger: 'click',
      duration: 1,
      elements: [
        {
          id: 'glucose-storage',
          type: 'text',
          content: '🌱 Energy for Growth',
          x: 30,
          y: 50,
          color: '#228B22',
        },
      ],
    },
  ],
};

export const heartPumpAnimation: AnimationSequence = {
  id: 'heart-pump-001',
  title: 'How the Heart Pumps Blood',
  topic: 'Biology - Cardiovascular System',
  description: 'Animation showing the cardiac cycle and blood flow through chambers',
  totalSteps: 4,
  autoPlay: false,
  difficulty: 'intermediate',
  tags: ['biology', 'heart', 'circulation'],
  steps: [
    {
      id: 'hp-1',
      step: 1,
      title: 'Diastole - Filling Phase',
      description: 'Blood fills the atria and ventricles relax.',
      narration: 'During diastole, the heart muscle relaxes and blood fills the chambers.',
      animationType: 'fade-in',
      trigger: 'click',
      duration: 1,
      elements: [
        {
          id: 'atria',
          type: 'shape',
          content: '❤️',
          x: 45,
          y: 20,
          width: 110,
          height: 80,
          color: '#FF6B9D',
        },
        {
          id: 'blood-in',
          type: 'text',
          content: 'Blood flows in ↓',
          x: 35,
          y: 80,
          color: '#E63946',
        },
      ],
    },
    {
      id: 'hp-2',
      step: 2,
      title: 'Atrial Contraction',
      description: 'Atria contract and push blood into ventricles.',
      narration: 'The atria contract, pumping blood into the ventricles below.',
      animationType: 'pulse',
      trigger: 'click',
      duration: 0.8,
      elements: [
        {
          id: 'contraction',
          type: 'text',
          content: '💪 Atria Squeeze',
          x: 35,
          y: 40,
          color: '#E63946',
        },
      ],
    },
    {
      id: 'hp-3',
      step: 3,
      title: 'Ventricular Contraction',
      description: 'Ventricles contract powerfully and push blood out of the heart.',
      narration: 'The ventricles contract forcefully, pushing blood to the lungs and body.',
      animationType: 'bounce',
      trigger: 'click',
      duration: 1,
      elements: [
        {
          id: 'ventricles',
          type: 'shape',
          content: '❤️',
          x: 40,
          y: 50,
          width: 120,
          height: 80,
          color: '#DC143C',
        },
        {
          id: 'blood-out',
          type: 'text',
          content: '↑ Blood pumps out',
          x: 35,
          y: 25,
          color: '#E63946',
        },
      ],
    },
    {
      id: 'hp-4',
      step: 4,
      title: 'Cycle Repeats',
      description: 'The cycle repeats for continuous circulation.',
      narration: 'This cycle repeats continuously, typically 60 to 100 times per minute in humans.',
      animationType: 'rotate',
      trigger: 'click',
      duration: 1.5,
      elements: [
        {
          id: 'cycle-complete',
          type: 'text',
          content: '↻ Complete Cycle',
          x: 40,
          y: 50,
          color: '#FFD700',
        },
      ],
    },
  ],
};

export const bubbleSortAnimation: AnimationSequence = {
  id: 'bubble-sort-001',
  title: 'Bubble Sort Algorithm',
  topic: 'Computer Science - Sorting',
  description: 'Step-by-step visualization of how bubble sort algorithm works',
  totalSteps: 6,
  autoPlay: false,
  difficulty: 'beginner',
  tags: ['computer-science', 'algorithms', 'sorting'],
  steps: [
    {
      id: 'bs-1',
      step: 1,
      title: 'Unsorted Array',
      description: 'We start with an unsorted list of numbers.',
      narration: "Let's sort these numbers using the bubble sort algorithm.",
      animationType: 'fade-in',
      trigger: 'click',
      duration: 1,
      elements: [
        {
          id: 'array-start',
          type: 'text',
          content: '[5, 2, 8, 1, 9]',
          x: 20,
          y: 50,
          color: '#1C1C1C',
        },
      ],
    },
    {
      id: 'bs-2',
      step: 2,
      title: 'First Pass - Compare 5 & 2',
      description: 'Compare adjacent elements. If left > right, swap them.',
      narration: 'We compare the first two numbers: 5 and 2.',
      animationType: 'slide-left',
      trigger: 'click',
      duration: 0.8,
      elements: [
        {
          id: 'compare-1',
          type: 'text',
          content: '5 > 2? YES → Swap',
          x: 25,
          y: 50,
          color: '#E63946',
        },
      ],
    },
    {
      id: 'bs-3',
      step: 3,
      title: 'First Pass - Compare 5 & 8',
      description: 'Continue comparing adjacent pairs.',
      narration: 'Now compare 5 and 8.',
      animationType: 'slide-left',
      trigger: 'click',
      duration: 0.8,
      elements: [
        {
          id: 'compare-2',
          type: 'text',
          content: '5 > 8? NO → No Swap',
          x: 25,
          y: 50,
          color: '#228B22',
        },
      ],
    },
    {
      id: 'bs-4',
      step: 4,
      title: 'First Pass Complete',
      description: 'After first pass, largest element reaches the end.',
      narration: 'After the first pass, the largest number (9) is in its correct position.',
      animationType: 'fade-in',
      trigger: 'click',
      duration: 1,
      elements: [
        {
          id: 'after-pass-1',
          type: 'text',
          content: '[2, 5, 1, 8, 9]',
          x: 20,
          y: 50,
          color: '#1C1C1C',
        },
        {
          id: 'sorted-9',
          type: 'text',
          content: '9 ✓',
          x: 75,
          y: 50,
          color: '#228B22',
        },
      ],
    },
    {
      id: 'bs-5',
      step: 5,
      title: 'Repeat for Remaining',
      description: 'Repeat the process for remaining unsorted portion.',
      narration: 'We repeat this process for the remaining unsorted elements.',
      animationType: 'pulse',
      trigger: 'click',
      duration: 1.5,
      elements: [
        {
          id: 'repeat-passes',
          type: 'text',
          content: 'Pass 2, 3, 4... ↻',
          x: 30,
          y: 50,
          color: '#E63946',
        },
      ],
    },
    {
      id: 'bs-6',
      step: 6,
      title: 'Sorted Array',
      description: 'All elements are now sorted in ascending order.',
      narration: 'The array is now completely sorted in ascending order.',
      animationType: 'scale',
      trigger: 'click',
      duration: 1,
      elements: [
        {
          id: 'array-sorted',
          type: 'text',
          content: '[1, 2, 5, 8, 9]',
          x: 20,
          y: 50,
          color: '#228B22',
        },
        {
          id: 'complete',
          type: 'text',
          content: '✓ Complete!',
          x: 60,
          y: 50,
          color: '#228B22',
        },
      ],
    },
  ],
};

export const projectileMotionAnimation: AnimationSequence = {
  id: 'projectile-motion-001',
  title: 'Projectile Motion',
  topic: 'Physics - Kinematics',
  description: 'Visualization of an object traveling through the air under gravity',
  totalSteps: 5,
  autoPlay: false,
  difficulty: 'intermediate',
  tags: ['physics', 'motion', 'gravity'],
  steps: [
    {
      id: 'pm-1',
      step: 1,
      title: 'Initial Velocity',
      description: 'Object is launched with initial velocity at an angle.',
      narration: 'An object is launched at an angle with initial velocity.',
      animationType: 'fade-in',
      trigger: 'click',
      duration: 1,
      elements: [
        {
          id: 'projectile',
          type: 'shape',
          content: '🔵',
          x: 10,
          y: 80,
          width: 30,
          height: 30,
          color: '#E63946',
        },
        {
          id: 'velocity-vector',
          type: 'text',
          content: 'v₀ →',
          x: 5,
          y: 75,
          color: '#1C1C1C',
        },
      ],
    },
    {
      id: 'pm-2',
      step: 2,
      title: 'Vertical Component',
      description: 'Gravity pulls the object downward (vertical acceleration).',
      narration: 'Gravity constantly pulls the object downward at 9.8 meters per second squared.',
      animationType: 'slide-up',
      trigger: 'click',
      duration: 1.5,
      elements: [
        {
          id: 'gravity-vector',
          type: 'text',
          content: '↓ g = 9.8 m/s²',
          x: 50,
          y: 40,
          color: '#E63946',
        },
      ],
    },
    {
      id: 'pm-3',
      step: 3,
      title: 'Parabolic Path',
      description: 'The combined effect creates a parabolic trajectory.',
      narration: 'The horizontal and vertical motions combine to create a parabolic path.',
      animationType: 'draw',
      trigger: 'click',
      duration: 2,
      elements: [
        {
          id: 'trajectory',
          type: 'text',
          content: '⌢ Parabolic Trajectory',
          x: 20,
          y: 30,
          color: '#1C1C1C',
        },
      ],
    },
    {
      id: 'pm-4',
      step: 4,
      title: 'Apex of Path',
      description: 'At the highest point, vertical velocity becomes zero.',
      narration: 'At the apex, the vertical velocity momentarily becomes zero.',
      animationType: 'pulse',
      trigger: 'click',
      duration: 1,
      elements: [
        {
          id: 'apex',
          type: 'text',
          content: 'Apex: vᵧ = 0',
          x: 40,
          y: 15,
          color: '#FFD700',
        },
      ],
    },
    {
      id: 'pm-5',
      step: 5,
      title: 'Landing',
      description: 'Object returns to ground level with downward velocity.',
      narration: 'The object follows the path until it returns to ground level.',
      animationType: 'bounce',
      trigger: 'click',
      duration: 1.5,
      elements: [
        {
          id: 'landing',
          type: 'text',
          content: 'Landing ✓',
          x: 80,
          y: 80,
          color: '#228B22',
        },
      ],
    },
  ],
};

export const animationTemplates: AnimationSequence[] = [
  photosynthesisAnimation,
  heartPumpAnimation,
  bubbleSortAnimation,
  projectileMotionAnimation,
];
